routes/web.php
<?php

//Admin

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {
        Route::get('/home', 'HomeController@index')->name('admin.home');
        Route::post('/home/send', 'HomeController@mail')->name('admin.send');
        Route::get('/profile', 'ProfileController@index')->name('admins.profile');
        Route::post('/profile', 'ProfileController@store')->name('admins.profileStore');
        Route::resource('/products', 'ProductController');
        Route::resource('/customize', 'CustomizeController');
        Route::resource('/roles', 'RoleController');
        Route::resource('/users', 'UserController');
        Route::resource('/specials', 'SpecialController');
        Route::resource('/admins', 'AdminController');
        Route::resource('/coupons', 'CouponController');
        Route::get('/orders','OrderController@index')->name('orders.index');
        Route::get('/finishedOrders','FinishedOrderController@index')->name('finishedOrders.index');
        Route::get('/destroyOrders','FinishedOrderController@destroy')->name('finishedOrders.destroy');
        Route::post('/finishedOrder/info','FinishedOrderController@info');
        Route::post('/orders/destroy','OrderController@destroy')->name('orders.destroy');
        Route::post('/orders/finish','OrderController@finish')->name('orders.finish');
        Route::post('/orders/onOff','OrderController@onOff');
        Route::post('/orders/status','OrderController@changeStatus');
        Route::post('/orders/info','OrderController@info');
        Route::post('/orders/clearAll','OrderController@clearAll');
        Route::post('/orders/done','OrderController@done')->name('orders.done');
        Route::get('/messages', 'MessageController@index')->name('message.index');
        Route::delete('/messages/{id}', 'MessageController@destroy')->name('message.destroy');

        Route::post('/coupon', 'CouponController@coupon')->name('coupon.coupon');
        Route::delete('/coupon', 'CouponController@delete')->name('coupon.delete');
        Route::get('/errors', function () { return view('errors.404Admin'); })->name('errors.admin');

        //Auth Admin
        Route::get('/login', 'Auth\LoginController@showLoginForm')->name('admin.login');
        Route::post('/login', 'Auth\LoginController@login');
        Route::post('/logout', 'Auth\LoginController@logout')->name('admin.logout');

        // Password Reset Routes...
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset');


        /*
        Route::get('/birthday', function() {
            Artisan::call('schedule:run');

            return 'yes';
        });
        */
    });
});


//User

Route::namespace('User')->group(function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('/home', 'HomeController@home')->name('home');
    Route::get('/menu', 'MenuController@menu')->name('user.categoryMenu');
    Route::get('/menu-category', 'MenuController@index')->name('user.menu');
    Route::post('/menu/popUp', 'MenuController@popUp')->name('user.popUp');
    Route::post('/menu/info', 'MenuController@addCart');
    Route::get('/cart', 'CartController@index')->name('cart.index');
    Route::post('/cart/favorites', 'CartController@favorites');
    Route::post('/cart/item', 'CartController@store')->name('cart.store');
    Route::post('/cart/remove', 'CartController@destroy')->name('cart.destroy');
    Route::get('/cart/remove_all', 'CartController@destroyAll')->name('cart.destroyAll');
    Route::post('/cart/changeQty', 'CartController@changeQty')->name('cart.changeQty');
    //Customize
    Route::get('/customize', 'CustomizeController@index')->name('customizeUser.index');
    Route::post('/customize', 'CustomizeController@setUp')->name('customizeUser.setUp');
    Route::post('/customize/size', 'CustomizeController@size');
    Route::post('/customize/store', 'CustomizeController@store')->name('customizeUser.store');
    Route::put('/customize/edit/{id}', 'CustomizeController@edit')->name('customizeUser.edit');
    Route::post('/customize/update', 'CustomizeController@updateRow')->name('customizeUser.updateRow');
    //Rewards
    Route::post('/customize/rewards-one', 'CustomizeController@rewardsOne')->name('customizeUser.rewardsOne');
    Route::post('/customize/rewards-two', 'CustomizeController@rewardsTwo')->name('customizeUser.rewardsTwo');
    Route::post('/customize/rewards-three', 'CustomizeController@rewardsThree')->name('customizeUser.rewardsThree');
    Route::put('/customize/rewards-one/{id}', 'CustomizeController@rewardsOneEdit')->name('customizeUser.rewardsOneEdit');
    Route::put('/customize/rewards-two/{id}', 'CustomizeController@rewardsTwoEdit')->name('customizeUser.rewardsTwoEdit');
    Route::put('/customize/rewards-three/{id}', 'CustomizeController@rewardsThreeEdit')->name('customizeUser.rewardsThreeEdit');

    Route::get('/contact', 'ContactUsController@index')->name('contactUser.index');
    Route::post('/contact', 'ContactUsController@store')->name('contactUser.store');

    Route::get('/reviews', function () { return view('user.reviews'); })->name('reviews');
    Route::get('/rewards', 'RewardsController@index')->name('rewards');
    Route::post('/rewards/dessert', 'RewardsController@dessert')->name('rewards.dessert');
    Route::get('/about-us', function () { return view('user.aboutUs'); })->name('aboutUs');
    Route::get('/errors', function () { return view('errors.404'); })->name('errors');


    Route::get('/cart/favorites', 'CartController@favorites')->name('cart.favorites');

    Route::get('/my-profile', 'FavoriteController@index')->name('favorite.index');
    Route::post('/my-favorites/add', 'FavoriteController@add')->name('favorite.add');
    Route::post('/my-favorites/delete', 'FavoriteController@delete');
    Route::post('/my-favorites/changeInfo', 'FavoriteController@changeInfo')->name('favorite.changeInfo');
    Route::post('/my-favorites/changePassword', 'FavoriteController@changePassword')->name('favorite.changePassword');
    Route::post('/my-favorites/changeEmail', 'FavoriteController@changeEmail')->name('favorite.changeEmail');

    Route::get('/pre-checkout', 'CheckOutController@preCheckout')->name('preCheckout');
    Route::post('/pre-checkout', 'CheckOutController@preCheckoutEdit')->name('preCheckoutEdit');
    Route::post('/checkout-done', 'CheckOutController@CheckoutDone')->name('CheckoutDone');

    Route::post('/thank-you', 'OrderController@store')->name('makeOrder');

    Route::get('/register/verify', 'Auth\RegisterController@verify')->name('verify');
    Route::get('/verify/{email}/{verifyToken}', 'Auth\RegisterController@sendEmailDone')->name('sendEmailDone');

    Route::post('/online-payment', 'PaymentController@pay')->name('onlinePayment');

    Route::get('/clear-cache', function() {
        Artisan::call('cache:clear');
        Artisan::call('view:clear');
        Artisan::call('config:clear');
        Artisan::call('route:clear');
    });
});

Route::get('/specials','Admin\SpecialController@specials')->name('specials');
Route::post('/specials/popUp','Admin\SpecialController@popUp');
Route::post('/specials/addToCart','Admin\SpecialController@addToCart')->name('special.add');
Route::post('/specials/YourOrder','Admin\SpecialController@YourOrder');
//Auth User

Auth::routes();

resources/views/admin/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    @include('admin.layouts.head')
</head>
<body class="hold-transition skin-purple sidebar-mini">
<div class="wrapper">
    @include('admin.layouts.header')
    @include('admin.layouts.sidebar')

        @section('body-part')
            @show

    @include('admin.layouts.footer')
</div>
@include('admin.layouts.script')
@section('script-part')
    @show
</body>
</html>

resources/views/admin/layouts/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
    </div>
</footer>

resources/views/admin/layouts/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>TripleA | Dashboard</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/font-awesome/css/font-awesome.min.css') }}">
<!-- Ionicons -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/Ionicons/css/ionicons.min.css') }}">
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('admin/dist/css/AdminLTE.min.css') }}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{{ asset('admin/dist/css/skins/_all-skins.min.css') }}">
<!-- Morris chart -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/morris.js/morris.css') }}">
<!-- jvectormap -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/jvectormap/jquery-jvectormap.css') }}">
<!-- Date Picker -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/bootstrap-daterangepicker/daterangepicker.css') }}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{{ asset('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">

<link rel="icon" href="{{ asset('/user/image/logic.png') }}">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
<script src="{{ asset('/js/cropit.js') }}"></script>

<style>
    .cropit-preview {
        background-color: #f8f8f8;
        background-size: cover;
        border: 1px solid #ccc;
        border-radius: 3px;
        margin-top: 7px;
        width: 400px;
        height: 270px;
    }

    .cropit-preview-image-container {
        cursor: move;
    }

    .image-size-label {
        margin-top: 10px;
    }

    input {
        display: block;
    }

    button[type="submit"] {
        margin-top: 10px;
    }

    #result {
        margin-top: 10px;
        width: 900px;
    }

    #result-data {
        display: block;
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
        word-wrap: break-word;
    }
    #myRange {
        -webkit-appearance: none;
        width: 100%;
        height: 25px;
        background: #d3d3d3;
        outline: none;
        opacity: 0.7;
        -webkit-transition: .2s;
        transition: opacity .2s;
    }

    #myRange:hover {
        opacity: 1;
    }

    #myRange::-webkit-slider-thumb {
        -webkit-appearance: none;
        appearance: none;
        width: 25px;
        height: 25px;
        background: orange;
        cursor: pointer;
    }

    #myRange::-moz-range-thumb {
        width: 25px;
        height: 25px;
        background: orange;
        cursor: pointer;
    }
    .switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

    .switch input {display:none;}

    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 26px;
        width: 26px;
        left: 4px;
        bottom: 4px;
        background-color: white;
        -webkit-transition: .4s;
        transition: .4s;
    }

    input:checked + .slider {
        background-color: rgb(96,92,168);
    }

    input:focus + .slider {
        box-shadow: 0 0 1px rgb(96,92,168);
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 34px;
    }

    .slider.round:before {
        border-radius: 50%;
    }
    #modal-css {
        width: 90%;
    }

    @media only screen and (max-width: 768px) {
        #modal-css {
            max-width: 100%;
        }
    }
    @media only screen and (max-width: 600px) {
        #modal-css {
            max-width: 100%;
        }
    }
    #exampleInfo>tbody>tr>td, #exampleInfo>tbody>tr>th, #exampleInfo>tfoot>tr>td, #exampleInfo>tfoot>tr>th, #exampleInfo>thead>tr>td, #exampleInfo>thead>tr>th{
        border: 1px solid darkgray;
    }
    #exampleInfo { border: 1px solid darkgray; }

</style>

resources/views/admin/layouts/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{ route('admin.home') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini" style="color: rgb(230,96,1)"><img src="{{ asset('/user/image/logic.png') }}" width="35px" height="35px"></span>
        <!-- logo for regular state and mobile devices
        <span class="logo-lg"><b>Triple</b>A</span>-->
        <span class="logo-lg"><img src="{{ asset('images/profile/logo.png') }}" width="130px" height="50px"></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ Storage::url(Auth::user()->image) }}" class="user-image" alt="User Image">
                        <span class="hidden-xs">{{ Auth::user()->name }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{ Storage::url(Auth::user()->image) }}" class="img-circle" alt="User Image">

                            <p>
                                {{ Auth::user()->name }} - {{ Auth::user()->role->display_name }}
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ route('admins.profile') }}" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a class="dropdown-item btn btn-default btn-flat" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    Sign out
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/layouts/script.blade.php
<!-- jQuery 3 -->
<script src="{{ asset('admin/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('admin/bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('admin/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- Morris.js charts -->
<script src="{{ asset('admin/bower_components/raphael/raphael.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/morris.js/morris.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('admin/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js') }}"></script>
<!-- jvectormap -->
<script src="{{ asset('admin/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
<script src="{{ asset('admin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('admin/bower_components/jquery-knob/dist/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('admin/bower_components/moment/min/moment.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<!-- datepicker -->
<script src="{{ asset('admin/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{ asset('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
<!-- Slimscroll -->
<script src="{{ asset('admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('admin/bower_components/fastclick/lib/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('admin/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('admin/dist/js/pages/dashboard.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('admin/dist/js/demo.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>

<!-- page script -->
<script>
    $(function () {
        $('#example1').DataTable()
        $('#example2').DataTable({
            'paging'      : true,
            'lengthChange': false,
            'searching'   : false,
            'ordering'    : true,
            'info'        : true,
            'autoWidth'   : false
        });


        $('.image-editor').cropit();

        $('form').submit(function() {
            // Move cropped image data to hidden input
            var imageData = $('.image-editor').cropit('export');
            $('.hidden-image-data').val(imageData);

            // Print HTTP request params
            var formValue = $(this).serialize();
            $('#result-data').text(formValue);

            // Prevent the form from actually submitting
            return false;
        });

    })

</script>

resources/views/admin/layouts/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ Storage::url(Auth::user()->image) }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->name }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li class="@yield('active1')"><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
            @can('admins.view', Auth::user())
                <li class="@yield('active5')"><a href="{{ route('admins.index') }}"><i class="fa fa-user-md"></i> <span>Admins</span></a></li>
            @endcan
            @can('products.view', Auth::user())
                <li class="@yield('activeCategory') treeview">
                    <a href="#">
                        <i class="fa fa-navicon"></i>
                        <span>Menu</span>
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="@yield('Pizza')"><a href="{{ route('products.index', ['category=pizza']) }}"><i class="fa fa-circle-o"></i> Pizza</a></li>
                        <li class="@yield('Salads')"><a href="{{ route('products.index', ['category=salads']) }}"><i class="fa fa-circle-o"></i> Salads</a></li>
                        <li class="@yield('Appetizers')"><a href="{{ route('products.index', ['category=appetizers']) }}"><i class="fa fa-circle-o"></i> Appetizers</a></li>
                        <li class="@yield('Nachos')"><a href="{{ route('products.index', ['category=nachos']) }}"><i class="fa fa-circle-o"></i> Nachos</a></li>
                        <li class="@yield('Calzones')"><a href="{{ route('products.index', ['category=calzones']) }}"><i class="fa fa-circle-o"></i> Calzones</a></li>
                        <li class="@yield('Garlic Fingers')"><a href="{{ route('products.index', ['category=garlic_fingers']) }}"><i class="fa fa-circle-o"></i> Garlic Fingers</a></li>
                        <li class="@yield('Chicken')"><a href="{{ route('products.index', ['category=chicken']) }}"><i class="fa fa-circle-o"></i> Chicken</a></li>
                        <li class="@yield('Chicken Wings')"><a href="{{ route('products.index', ['category=chicken_wings']) }}"><i class="fa fa-circle-o"></i> Chicken Wings</a></li>
                        <li class="@yield('Sandwiches')"><a href="{{ route('products.index', ['category=sandwiches']) }}"><i class="fa fa-circle-o"></i> Sandwiches</a></li>
                        <li class="@yield('Subs')"><a href="{{ route('products.index', ['category=subs']) }}"><i class="fa fa-circle-o"></i> Subs</a></li>
                        <li class="@yield('Wraps')"><a href="{{ route('products.index', ['category=wraps']) }}"><i class="fa fa-circle-o"></i> Wraps</a></li>
                        <li class="@yield('Donairs')"><a href="{{ route('products.index', ['category=donairs']) }}"><i class="fa fa-circle-o"></i> Donairs</a></li>
                        <li class="@yield('Poutine')"><a href="{{ route('products.index', ['category=poutine']) }}"><i class="fa fa-circle-o"></i> Poutine</a></li>
                        <li class="@yield('Seafood')"><a href="{{ route('products.index', ['category=seafood']) }}"><i class="fa fa-circle-o"></i> Seafood</a></li>
                        <li class="@yield('Burgers')"><a href="{{ route('products.index', ['category=burgers']) }}"><i class="fa fa-circle-o"></i> Burgers</a></li>
                        <li class="@yield('Drinks')"><a href="{{ route('products.index', ['category=drinks']) }}"><i class="fa fa-circle-o"></i> Drinks</a></li>
                        <li class="@yield('Munchies')"><a href="{{ route('products.index', ['category=munchies']) }}"><i class="fa fa-circle-o"></i> Munchies</a></li>
                        <li class="@yield('Desserts')"><a href="{{ route('products.index', ['category=desserts']) }}"><i class="fa fa-circle-o"></i> Desserts</a></li>
                        <li class="@yield('Sauces')"><a href="{{ route('products.index', ['category=sauces']) }}"><i class="fa fa-circle-o"></i> Sauces</a></li>
                    </ul>
                </li>
            @endcan
            @can('customizes.view', Auth::user())
                <li class="@yield('active12')"><a href="{{ route('specials.index') }}"><i class="fa fa-diamond"></i> <span>Specials</span></a></li>
            @endcan
            @can('customizes.view', Auth::user())
                <li class="@yield('active9')"><a href="{{ route('customize.index') }}"><i class="fa fa-pie-chart"></i> <span>Pizza Toppings</span></a></li>
            @endcan
            @can('orders', Auth::user())
                <li class="@yield('active4')"><a href="{{ route('orders.index') }}"><i class="fa fa-shopping-cart"></i> <span>Online Orders</span></a></li>
            @endcan
            @can('orders', Auth::user())
                <li class="@yield('active8')"><a href="{{ route('finishedOrders.index') }}"><i class="fa fa-cart-arrow-down"></i> <span>Order History</span></a></li>
            @endcan
            @can('roles.view', Auth::user())
                <li class="@yield('active6')"><a href="{{ route('roles.index') }}"><i class="fa  fa-user-secret"></i> <span>Roles</span></a></li>
            @endcan
            @can('messages', Auth::user())
                <li class="@yield('active7')"><a href="{{ route('message.index') }}"><i class="fa fa-envelope-o"></i> <span>Email</span></a></li>
            @endcan
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>