routes/web.php
<?php

//Admin

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {
        Route::get('/home', 'HomeController@index')->name('admin.home');
        Route::post('/home/send', 'HomeController@mail')->name('admin.send');
        Route::get('/profile', 'ProfileController@index')->name('admins.profile');
        Route::post('/profile', 'ProfileController@store')->name('admins.profileStore');
        Route::resource('/products', 'ProductController');
        Route::resource('/customize', 'CustomizeController');
        Route::resource('/roles', 'RoleController');
        Route::resource('/users', 'UserController');
        Route::resource('/specials', 'SpecialController');
        Route::resource('/admins', 'AdminController');
        Route::resource('/coupons', 'CouponController');
        Route::get('/orders','OrderController@index')->name('orders.index');
        Route::get('/finishedOrders','FinishedOrderController@index')->name('finishedOrders.index');
        Route::get('/destroyOrders','FinishedOrderController@destroy')->name('finishedOrders.destroy');
        Route::post('/finishedOrder/info','FinishedOrderController@info');
        Route::post('/orders/destroy','OrderController@destroy')->name('orders.destroy');
        Route::post('/orders/finish','OrderController@finish')->name('orders.finish');
        Route::post('/orders/onOff','OrderController@onOff');
        Route::post('/orders/status','OrderController@changeStatus');
        Route::post('/orders/info','OrderController@info');
        Route::post('/orders/clearAll','OrderController@clearAll');
        Route::post('/orders/done','OrderController@done')->name('orders.done');
        Route::get('/messages', 'MessageController@index')->name('message.index');
        Route::delete('/messages/{id}', 'MessageController@destroy')->name('message.destroy');

        Route::post('/coupon', 'CouponController@coupon')->name('coupon.coupon');
        Route::delete('/coupon', 'CouponController@delete')->name('coupon.delete');
        Route::get('/errors', function () { return view('errors.404Admin'); })->name('errors.admin');

        //Auth Admin
        Route::get('/login', 'Auth\LoginController@showLoginForm')->name('admin.login');
        Route::post('/login', 'Auth\LoginController@login');
        Route::post('/logout', 'Auth\LoginController@logout')->name('admin.logout');

        // Password Reset Routes...
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset');


        /*
        Route::get('/birthday', function() {
            Artisan::call('schedule:run');

            return 'yes';
        });
        */
    });
});


//User

Route::namespace('User')->group(function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('/home', 'HomeController@home')->name('home');
    Route::get('/menu', 'MenuController@menu')->name('user.categoryMenu');
    Route::get('/menu-category', 'MenuController@index')->name('user.menu');
    Route::post('/menu/popUp', 'MenuController@popUp')->name('user.popUp');
    Route::post('/menu/info', 'MenuController@addCart');
    Route::get('/cart', 'CartController@index')->name('cart.index');
    Route::post('/cart/favorites', 'CartController@favorites');
    Route::post('/cart/item', 'CartController@store')->name('cart.store');
    Route::post('/cart/remove', 'CartController@destroy')->name('cart.destroy');
    Route::get('/cart/remove_all', 'CartController@destroyAll')->name('cart.destroyAll');
    Route::post('/cart/changeQty', 'CartController@changeQty')->name('cart.changeQty');
    //Customize
    Route::get('/customize', 'CustomizeController@index')->name('customizeUser.index');
    Route::post('/customize', 'CustomizeController@setUp')->name('customizeUser.setUp');
    Route::post('/customize/size', 'CustomizeController@size');
    Route::post('/customize/store', 'CustomizeController@store')->name('customizeUser.store');
    Route::put('/customize/edit/{id}', 'CustomizeController@edit')->name('customizeUser.edit');
    Route::post('/customize/update', 'CustomizeController@updateRow')->name('customizeUser.updateRow');
    //Rewards
    Route::post('/customize/rewards-one', 'CustomizeController@rewardsOne')->name('customizeUser.rewardsOne');
    Route::post('/customize/rewards-two', 'CustomizeController@rewardsTwo')->name('customizeUser.rewardsTwo');
    Route::post('/customize/rewards-three', 'CustomizeController@rewardsThree')->name('customizeUser.rewardsThree');
    Route::put('/customize/rewards-one/{id}', 'CustomizeController@rewardsOneEdit')->name('customizeUser.rewardsOneEdit');
    Route::put('/customize/rewards-two/{id}', 'CustomizeController@rewardsTwoEdit')->name('customizeUser.rewardsTwoEdit');
    Route::put('/customize/rewards-three/{id}', 'CustomizeController@rewardsThreeEdit')->name('customizeUser.rewardsThreeEdit');

    Route::get('/contact', 'ContactUsController@index')->name('contactUser.index');
    Route::post('/contact', 'ContactUsController@store')->name('contactUser.store');

    Route::get('/reviews', function () { return view('user.reviews'); })->name('reviews');
    Route::get('/rewards', 'RewardsController@index')->name('rewards');
    Route::post('/rewards/dessert', 'RewardsController@dessert')->name('rewards.dessert');
    Route::get('/about-us', function () { return view('user.aboutUs'); })->name('aboutUs');
    Route::get('/errors', function () { return view('errors.404'); })->name('errors');


    Route::get('/cart/favorites', 'CartController@favorites')->name('cart.favorites');

    Route::get('/my-profile', 'FavoriteController@index')->name('favorite.index');
    Route::post('/my-favorites/add', 'FavoriteController@add')->name('favorite.add');
    Route::post('/my-favorites/delete', 'FavoriteController@delete');
    Route::post('/my-favorites/changeInfo', 'FavoriteController@changeInfo')->name('favorite.changeInfo');
    Route::post('/my-favorites/changePassword', 'FavoriteController@changePassword')->name('favorite.changePassword');
    Route::post('/my-favorites/changeEmail', 'FavoriteController@changeEmail')->name('favorite.changeEmail');

    Route::get('/pre-checkout', 'CheckOutController@preCheckout')->name('preCheckout');
    Route::post('/pre-checkout', 'CheckOutController@preCheckoutEdit')->name('preCheckoutEdit');
    Route::post('/checkout-done', 'CheckOutController@CheckoutDone')->name('CheckoutDone');

    Route::post('/thank-you', 'OrderController@store')->name('makeOrder');

    Route::get('/register/verify', 'Auth\RegisterController@verify')->name('verify');
    Route::get('/verify/{email}/{verifyToken}', 'Auth\RegisterController@sendEmailDone')->name('sendEmailDone');

    Route::post('/online-payment', 'PaymentController@pay')->name('onlinePayment');

    Route::get('/clear-cache', function() {
        Artisan::call('cache:clear');
        Artisan::call('view:clear');
        Artisan::call('config:clear');
        Artisan::call('route:clear');
    });
});

Route::get('/specials','Admin\SpecialController@specials')->name('specials');
Route::post('/specials/popUp','Admin\SpecialController@popUp');
Route::post('/specials/addToCart','Admin\SpecialController@addToCart')->name('special.add');
Route::post('/specials/YourOrder','Admin\SpecialController@YourOrder');
//Auth User

Auth::routes();

app/Http/Controllers/Admin/CustomizeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Customize;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class CustomizeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admins');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->can('customizes.view')) {
            $customizes = Customize::all();
            return view('admin.customize.customize', compact('customizes'));
        }else {
            return view('errors.404Admin');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->can('customizes.view')) {

            return view('admin.customize.new');
        }else {
            return view('errors.404Admin');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Auth::user()->can('customizes.view')) {

            $validatedData = $request->validate([
                'name' => 'required'
            ]);

            $customize = new Customize();

            $customize->name = $request->name;
            //$customize->size = $request->size;
            //$customize->for = $request->for;
            $customize->customize_price = $request->customize_price;
            $customize->medium_price = $request->medium_price;
            $customize->large_price = $request->large_price;
            $customize->xlg_price = $request->xlg_price;
            $customize->regular_premium = $request->regular_premium;
            $customize->customize_category = $request->customize_category;

            $customize->save();

            return redirect()->back()->with('message', 'Customize successfully added!');
        }else {
            return view('errors.404Admin');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->can('customizes.view')) {

            $customize = Customize::where('id', $id)->first();

            return view('admin.customize.update', compact('customize'));
        }else {
            return view('errors.404Admin');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (Auth::user()->can('customizes.view')) {

            $validatedData = $request->validate([
                'name' => 'required'
            ]);

            $customize = Customize::where('id', $id)->first();

            $customize->name = $request->name;
            //$customize->display_name = $request->display_name;
            //$customize->for = $request->for;
            $customize->customize_price = $request->customize_price;
            $customize->medium_price = $request->medium_price;
            $customize->large_price = $request->large_price;
            $customize->xlg_price = $request->xlg_price;
            $customize->regular_premium = $request->regular_premium;
            $customize->customize_category = $request->customize_category;

            $customize->save();

            return redirect()->route('customize.index')->with('message', 'Customize successfully updated!');
        }else {
            return view('errors.404Admin');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Auth::user()->can('customizes.view')) {

            $customize = Customize::where('id', $id)->first();

            $customize->delete();

            return redirect()->back()->with('message', 'Customize successfully deleted!');
        } else {
            return view('errors.404Admin');
        }
    }
}

resources/views/admin/customize/customize.blade.php
@extends('admin.layouts.app')
@section('active9','active')
@section('body-part')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Pizza Toppings
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Customizes</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">All Toppings</h3>
                            <br>
                            <div class="col-sm-1">
                                    <a href="{{ route('customize.create') }}">
                                        <button class="btn btn-success btn-flat">New</button>
                                    </a>
                            </div>
                            <div class="col-sm-6 col-sm-offset-2">
                                @include('admin.layouts.errors.error')
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="table-responsive">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Small Price($)</th>
                                        <th>Medium Price($)</th>
                                        <th>Large Price($)</th>
                                        <th>XLG Price($)</th>
                                        <th>Regular or Premium</th>
                                        <th>Customize Category</th>
                                            <th>Update</th>
                                            <th>Delete</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($customizes as $customize)
                                        <tr>
                                            <td>{{ $loop->index+1 }}</td>
                                            <td>{{ $customize->name }}</td>
                                            <td>{{ number_format($customize->customize_price,2) }}</td>
                                            <td>{{ number_format($customize->medium_price,2) }}</td>
                                            <td>{{ number_format($customize->large_price,2) }}</td>
                                            <td>{{ number_format($customize->xlg_price,2) }}</td>
                                            <td>{{ $customize->regular_premium }}</td>
                                            <td>{{ $customize->customize_category }}</td>
                                                <td>
                                                    <a href="{{ route('customize.edit',$customize->id) }}">
                                                        <button class="btn btn-warning btn-block btn-flat">Update</button>
                                                    </a>
                                                </td>
                                                <td>
                                                    <form id="delete-form-{{ $customize->id }}" method="post" action="{{ route('customize.destroy',$customize->id) }}" style="display: none;">
                                                        @csrf
                                                        {{ method_field('DELETE') }}
                                                    </form>
                                                    <a href="" onclick="if(confirm('Do you really want to delete this customize?')){
                                                            event.preventDefault();
                                                            document.getElementById('delete-form-{{ $customize->id }}').submit();
                                                            }else{
                                                            event.preventDefault();
                                                            }">
                                                        <button class="btn btn-danger btn-flat btn-block">Delete</button>
                                                    </a>
                                                </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Small Price($)</th>
                                        <th>Medium Price($)</th>
                                        <th>Large Price($)</th>
                                        <th>XLG Price($)</th>
                                        <th>Regular or premium</th>
                                        <th>Customize Category</th>
                                            <th>Update</th>
                                            <th>Delete</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

@endsection

resources/views/admin/customize/new.blade.php
@extends('admin.layouts.app')
@section('active9','active')
@section('body-part')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                New Pizza Topping
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="{{ route('customize.index') }}">Customizes</a></li>
                <li class="active">New</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-yellow">
                        <div class="box-header with-border">
                            <div class="col-sm-1">
                                <a href="{{ route('customize.index') }}">
                                    <button class="btn btn-warning btn-flat btn-block">Back</button>
                                </a>
                            </div>
                            <div class="col-sm-7 col-sm-offset-2">
                                @include('admin.layouts.errors.error')
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('customize.store') }}" method="POST">
                            @csrf
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Name</label>
                                    <input type="text" name="name" class="form-control" id="exampleInputName" placeholder="Enter name" required>
                                </div>
                                <div class="form-group">
                                    <label>Customize category</label>
                                    <select class="form-control" name="customize_category">
                                        <option value="Cheeses" selected>Cheeses</option>
                                        <option value="Meats">Meats</option>
                                        <option value="Veggies">Veggies</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Customize category</label>
                                    <select class="form-control" name="regular_premium">
                                        <option value="regular" selected>Regular</option>
                                        <option value="premium">Premium</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Small Price</label>
                                    <input type="number" name="customize_price" step="any" value="0.80" class="form-control" id="exampleInputName" placeholder="Enter customize small price" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Medium Price</label>
                                    <input type="number" name="medium_price" step="any" value="1.25" class="form-control" id="exampleInputName" placeholder="Enter customize medium price" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Large Price</label>
                                    <input type="number" name="large_price" step="any" value="1.60" class="form-control" id="exampleInputName" placeholder="Enter customize large price" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">XLG Price</label>
                                    <input type="number" name="xlg_price" step="any" value="1.95" class="form-control" id="exampleInputName" placeholder="Enter customize xlg price" required>
                                </div>

                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-flat">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/customize/update.blade.php
@extends('admin.layouts.app')
@section('active9','active')
@section('body-part')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Update Pizza Topping
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="{{ route('customize.index') }}">Customizes</a></li>
                <li class="active">Update</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-yellow">
                        <div class="box-header with-border">
                            <div class="col-sm-1">
                                <a href="{{ route('customize.index') }}">
                                    <button class="btn btn-warning btn-flat btn-block">Back</button>
                                </a>
                            </div>
                            <div class="col-sm-7 col-sm-offset-2">
                                @include('admin.layouts.errors.error')
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('customize.update',$customize->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Name</label>
                                    <input type="text" name="name" class="form-control" id="exampleInputName" placeholder="Enter display name" value="{{ $customize->name }}" required>
                                </div>
                                <div class="form-group">
                                    <label>Customize category</label>
                                    <select class="form-control" name="customize_category">
                                        <option value="Cheeses" @if($customize->customize_category == 'Cheeses') selected @endif>Cheeses</option>
                                        <option value="Meats" @if($customize->customize_category == 'Meats') selected @endif>Meats</option>
                                        <option value="Veggies" @if($customize->customize_category == 'Veggies') selected @endif>Veggies</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Customize category</label>
                                    <select class="form-control" name="regular_premium">
                                        <option value="regular" @if($customize->regular_premium == 'regular') selected @endif>Regular</option>
                                        <option value="premium" @if($customize->regular_premium == 'premium') selected @endif>Premium</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Small Price</label>
                                    <input type="number" name="customize_price" step="any" class="form-control" id="exampleInputName" placeholder="Enter customize price" value="{{ number_format($customize->customize_price,2) }}" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Medium Price</label>
                                    <input type="number" name="medium_price" step="any" class="form-control" id="exampleInputName" placeholder="Enter customize price" value="{{ number_format($customize->medium_price,2) }}" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Large Price</label>
                                    <input type="number" name="large_price" step="any" class="form-control" id="exampleInputName" placeholder="Enter customize price" value="{{ number_format($customize->large_price,2) }}" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">XLG Price</label>
                                    <input type="number" name="xlg_price" step="any" class="form-control" id="exampleInputName" placeholder="Enter customize price" value="{{ number_format($customize->xlg_price,2) }}" required>
                                </div>

                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-flat">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>
@endsection