routes/web.php
<?php

//Admin

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {
        Route::get('/home', 'HomeController@index')->name('admin.home');
        Route::post('/home/send', 'HomeController@mail')->name('admin.send');
        Route::get('/profile', 'ProfileController@index')->name('admins.profile');
        Route::post('/profile', 'ProfileController@store')->name('admins.profileStore');
        Route::resource('/products', 'ProductController');
        Route::resource('/customize', 'CustomizeController');
        Route::resource('/roles', 'RoleController');
        Route::resource('/users', 'UserController');
        Route::resource('/specials', 'SpecialController');
        Route::resource('/admins', 'AdminController');
        Route::resource('/coupons', 'CouponController');
        Route::get('/orders','OrderController@index')->name('orders.index');
        Route::get('/finishedOrders','FinishedOrderController@index')->name('finishedOrders.index');
        Route::get('/destroyOrders','FinishedOrderController@destroy')->name('finishedOrders.destroy');
        Route::post('/finishedOrder/info','FinishedOrderController@info');
        Route::post('/orders/destroy','OrderController@destroy')->name('orders.destroy');
        Route::post('/orders/finish','OrderController@finish')->name('orders.finish');
        Route::post('/orders/onOff','OrderController@onOff');
        Route::post('/orders/status','OrderController@changeStatus');
        Route::post('/orders/info','OrderController@info');
        Route::post('/orders/clearAll','OrderController@clearAll');
        Route::post('/orders/done','OrderController@done')->name('orders.done');
        Route::get('/messages', 'MessageController@index')->name('message.index');
        Route::delete('/messages/{id}', 'MessageController@destroy')->name('message.destroy');

        Route::post('/coupon', 'CouponController@coupon')->name('coupon.coupon');
        Route::delete('/coupon', 'CouponController@delete')->name('coupon.delete');
        Route::get('/errors', function () { return view('errors.404Admin'); })->name('errors.admin');

        //Auth Admin
        Route::get('/login', 'Auth\LoginController@showLoginForm')->name('admin.login');
        Route::post('/login', 'Auth\LoginController@login');
        Route::post('/logout', 'Auth\LoginController@logout')->name('admin.logout');

        // Password Reset Routes...
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset');


        /*
        Route::get('/birthday', function() {
            Artisan::call('schedule:run');

            return 'yes';
        });
        */
    });
});


//User

Route::namespace('User')->group(function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('/home', 'HomeController@home')->name('home');
    Route::get('/menu', 'MenuController@menu')->name('user.categoryMenu');
    Route::get('/menu-category', 'MenuController@index')->name('user.menu');
    Route::post('/menu/popUp', 'MenuController@popUp')->name('user.popUp');
    Route::post('/menu/info', 'MenuController@addCart');
    Route::get('/cart', 'CartController@index')->name('cart.index');
    Route::post('/cart/favorites', 'CartController@favorites');
    Route::post('/cart/item', 'CartController@store')->name('cart.store');
    Route::post('/cart/remove', 'CartController@destroy')->name('cart.destroy');
    Route::get('/cart/remove_all', 'CartController@destroyAll')->name('cart.destroyAll');
    Route::post('/cart/changeQty', 'CartController@changeQty')->name('cart.changeQty');
    //Customize
    Route::get('/customize', 'CustomizeController@index')->name('customizeUser.index');
    Route::post('/customize', 'CustomizeController@setUp')->name('customizeUser.setUp');
    Route::post('/customize/size', 'CustomizeController@size');
    Route::post('/customize/store', 'CustomizeController@store')->name('customizeUser.store');
    Route::put('/customize/edit/{id}', 'CustomizeController@edit')->name('customizeUser.edit');
    Route::post('/customize/update', 'CustomizeController@updateRow')->name('customizeUser.updateRow');
    //Rewards
    Route::post('/customize/rewards-one', 'CustomizeController@rewardsOne')->name('customizeUser.rewardsOne');
    Route::post('/customize/rewards-two', 'CustomizeController@rewardsTwo')->name('customizeUser.rewardsTwo');
    Route::post('/customize/rewards-three', 'CustomizeController@rewardsThree')->name('customizeUser.rewardsThree');
    Route::put('/customize/rewards-one/{id}', 'CustomizeController@rewardsOneEdit')->name('customizeUser.rewardsOneEdit');
    Route::put('/customize/rewards-two/{id}', 'CustomizeController@rewardsTwoEdit')->name('customizeUser.rewardsTwoEdit');
    Route::put('/customize/rewards-three/{id}', 'CustomizeController@rewardsThreeEdit')->name('customizeUser.rewardsThreeEdit');

    Route::get('/contact', 'ContactUsController@index')->name('contactUser.index');
    Route::post('/contact', 'ContactUsController@store')->name('contactUser.store');

    Route::get('/reviews', function () { return view('user.reviews'); })->name('reviews');
    Route::get('/rewards', 'RewardsController@index')->name('rewards');
    Route::post('/rewards/dessert', 'RewardsController@dessert')->name('rewards.dessert');
    Route::get('/about-us', function () { return view('user.aboutUs'); })->name('aboutUs');
    Route::get('/errors', function () { return view('errors.404'); })->name('errors');


    Route::get('/cart/favorites', 'CartController@favorites')->name('cart.favorites');

    Route::get('/my-profile', 'FavoriteController@index')->name('favorite.index');
    Route::post('/my-favorites/add', 'FavoriteController@add')->name('favorite.add');
    Route::post('/my-favorites/delete', 'FavoriteController@delete');
    Route::post('/my-favorites/changeInfo', 'FavoriteController@changeInfo')->name('favorite.changeInfo');
    Route::post('/my-favorites/changePassword', 'FavoriteController@changePassword')->name('favorite.changePassword');
    Route::post('/my-favorites/changeEmail', 'FavoriteController@changeEmail')->name('favorite.changeEmail');

    Route::get('/pre-checkout', 'CheckOutController@preCheckout')->name('preCheckout');
    Route::post('/pre-checkout', 'CheckOutController@preCheckoutEdit')->name('preCheckoutEdit');
    Route::post('/checkout-done', 'CheckOutController@CheckoutDone')->name('CheckoutDone');

    Route::post('/thank-you', 'OrderController@store')->name('makeOrder');

    Route::get('/register/verify', 'Auth\RegisterController@verify')->name('verify');
    Route::get('/verify/{email}/{verifyToken}', 'Auth\RegisterController@sendEmailDone')->name('sendEmailDone');

    Route::post('/online-payment', 'PaymentController@pay')->name('onlinePayment');

    Route::get('/clear-cache', function() {
        Artisan::call('cache:clear');
        Artisan::call('view:clear');
        Artisan::call('config:clear');
        Artisan::call('route:clear');
    });
});

Route::get('/specials','Admin\SpecialController@specials')->name('specials');
Route::post('/specials/popUp','Admin\SpecialController@popUp');
Route::post('/specials/addToCart','Admin\SpecialController@addToCart')->name('special.add');
Route::post('/specials/YourOrder','Admin\SpecialController@YourOrder');
//Auth User

Auth::routes();

resources/views/admin/admins/admins.blade.php
@extends('admin.layouts.app')
@section('active5','active')
@section('body-part')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Admins
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Admins</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">All Admins</h3>
                            <br>
                            <div class="col-sm-1">
                                    <a href="{{ route('admins.create') }}">
                                        <button class="btn btn-success btn-flat">New</button>
                                    </a>
                            </div>
                            <div class="col-sm-6 col-sm-offset-2">
                                @include('admin.layouts.errors.error')
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="table-responsive">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Image</th>
                                        <th>Role</th>
                                            <th>Update</th>
                                            <th>Delete</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($admins as $admin)
                                        <tr>
                                            <td>{{ $admin->name }}</td>
                                            <td>{{ $admin->email }}</td>
                                            <td><img src="{{ Storage::url($admin->image) }}" width="100px" height="100px" alt="User Image"></td>
                                            <td>{{ $admin->role->display_name }}</td>
                                                <td>
                                                    <a href="{{ route('admins.edit',$admin->id) }}">
                                                        <button class="btn btn-warning btn-block btn-flat">Update</button>
                                                    </a>
                                                </td>
                                                <td>
                                                    <form id="delete-form-{{ $admin->id }}" method="post" action="{{ route('admins.destroy',$admin->id) }}" style="display: none;">
                                                        @csrf
                                                        {{ method_field('DELETE') }}
                                                    </form>
                                                    <a href="" onclick="if(confirm('Do you really want to delete this admin?')){
                                                            event.preventDefault();
                                                            document.getElementById('delete-form-{{ $admin->id }}').submit();
                                                            }else{
                                                            event.preventDefault();
                                                            }">
                                                        <button class="btn btn-danger btn-flat btn-block">Delete</button>
                                                    </a>
                                                </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Image</th>
                                        <th>Role</th>
                                            <th>Update</th>
                                            <th>Delete</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

@endsection

resources/views/admin/admins/new.blade.php
@extends('admin.layouts.app')
@section('active5','active')
@section('body-part')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                New Admin
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="{{ route('admins.index') }}">Admins</a></li>
                <li class="active">New</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-yellow">
                        <div class="box-header with-border">
                            <div class="col-sm-1">
                                <a href="{{ route('admins.index') }}">
                                    <button class="btn btn-warning btn-flat btn-block">Back</button>
                                </a>
                            </div>
                            <div class="col-sm-7 col-sm-offset-2">
                                @include('admin.layouts.errors.error')
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('admins.store') }}" method="POST">
                            @csrf
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Name</label>
                                    <input type="text" name="name" class="form-control" id="exampleInputName" placeholder="Enter name" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email</label>
                                    <input type="email" name="email" class="form-control" id="exampleInputName" placeholder="Enter email" required>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Password</label>
                                    <input type="password" name="password" class="form-control" id="exampleInputName" placeholder="Enter password" required>
                                </div>

                                <div class="form-group">
                                    <label>Role</label>
                                    <select class="form-control" name="role" required>
                                        @foreach($roles as $role)
                                            <option value="{{ $role->id }}">{{ $role->display_name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-flat">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/admins/profile.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>TripleA | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/font-awesome/css/font-awesome.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/Ionicons/css/ionicons.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('admin/dist/css/AdminLTE.min.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('admin/dist/css/skins/_all-skins.min.css') }}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/morris.js/morris.css') }}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/jvectormap/jquery-jvectormap.css') }}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/bootstrap-daterangepicker/daterangepicker.css') }}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{ asset('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="{{ asset('/js/cropit.js') }}"></script>

    <style>
        .cropit-preview {
            background-color: #f8f8f8;
            background-size: cover;
            border: 1px solid #ccc;
            border-radius: 3px;
            margin-top: 7px;
            width: 300px;
            height: 300px;
        }

        .cropit-preview-image-container {
            cursor: move;
        }

        .image-size-label {
            margin-top: 10px;
        }

        input {
            display: block;
        }

        button[type="submit"] {
            margin-top: 10px;
        }

        #result {
            margin-top: 10px;
            width: 900px;
        }

        #result-data {
            display: block;
            overflow: hidden;
            white-space: nowrap;
            text-overflow: ellipsis;
            word-wrap: break-word;
        }
        .slidecontainer {
            width: 100%;
        }

        #myRange {
            -webkit-appearance: none;
            width: 100%;
            height: 25px;
            background: #d3d3d3;
            outline: none;
            opacity: 0.7;
            -webkit-transition: .2s;
            transition: opacity .2s;
        }

        #myRange:hover {
            opacity: 1;
        }

        #myRange::-webkit-slider-thumb {
            -webkit-appearance: none;
            appearance: none;
            width: 25px;
            height: 25px;
            background: dodgerblue;
            cursor: pointer;
        }

        #myRange::-moz-range-thumb {
            width: 25px;
            height: 25px;
            background: dodgerblue;
            cursor: pointer;
        }
    </style>

</head>
<body class="hold-transition skin-purple sidebar-mini">
<div class="wrapper">
    @include('admin.layouts.header')
    @include('admin.layouts.sidebar')

    @section('body-part')
        <div class="content-wrapper">

            <!-- Main content -->
            <section class="content">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- Profile Image -->
                        <div class="col-md-6 col-md-offset-3">
                            <div class="box box-warning">
                                <div class="box-body box-profile">
                                    <div class="col-sm-8 col-sm-offset-2">
                                        <form action="{{ route('admins.profileStore') }}" method="POST" id="form-id">
                                            @csrf
                                            <input type="hidden" name="id" value="{{ Auth::user()->id }}">
                                            <div class="image-editor">
                                                <div class="cropit-profile"><img src="{{ Storage::url(Auth::user()->image) }}"></div>
                                                <div class="cropit-preview" style="display: none"></div>
                                                <br>
                                                <input type="range" id="myRange" class="cropit-image-zoom-input">
                                                <input type="hidden" name="image-data" class="hidden-image-data" />
                                                <input type="file" name="image" id="image_input" class="cropit-image-input" required>

                                            </div>

                                            <h3 class="profile-username text-center">{{ Auth::user()->name }}</h3>

                                            <p class="text-muted text-center">{{ Auth::user()->role->display_name }}</p>

                                            <a href=""><button type="submit" class="btn btn-primary btn-block btn-flat"><b>Change Picture</b></button></a>
                                        </form>

                                    </div>
                                </div>
                                <!-- /.box-body -->
                            </div>
                        </div>
                        <!-- /.box -->
                    </div>
                </div>
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    @show

    @include('admin.layouts.footer')
</div>

<script>
    $(function() {
        $('#example1').DataTable()
        $('#example2').DataTable({
            'paging'      : true,
            'lengthChange': false,
            'searching'   : false,
            'ordering'    : true,
            'info'        : true,
            'autoWidth'   : false
        });

        $("#image_input").click(function () {
            $(".cropit-profile").hide(20);
            $(".cropit-preview").show(20);
        });

        $('.image-editor').cropit({'minZoom':2});

        $('#form-id').submit(function() {
            // Move cropped image data to hidden input
            var imageData = $('.image-editor').cropit('export');

            $('.hidden-image-data').val(imageData);

            // Print HTTP request params
            var formValue = $(this).serialize();
            $('#result-data').text(formValue);

            // Prevent the form from actually submitting
            return true;
        });
    });
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('admin/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- Morris.js charts -->
<script src="{{ asset('admin/bower_components/raphael/raphael.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/morris.js/morris.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('admin/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js') }}"></script>
<!-- jvectormap -->
<script src="{{ asset('admin/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
<script src="{{ asset('admin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('admin/bower_components/jquery-knob/dist/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('admin/bower_components/moment/min/moment.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<!-- datepicker -->
<script src="{{ asset('admin/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{ asset('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
<!-- Slimscroll -->
<script src="{{ asset('admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('admin/bower_components/fastclick/lib/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('admin/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('admin/dist/js/pages/dashboard.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('admin/dist/js/demo.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>

</body>
</html>

resources/views/admin/admins/update.blade.php
@extends('admin.layouts.app')
@section('active5','active')
@section('body-part')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Update Admin
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="{{ route('admins.index') }}">Admins</a></li>
                <li class="active">New</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-yellow">
                        <div class="box-header with-border">
                            <div class="col-sm-1">
                                <a href="{{ route('admins.index') }}">
                                    <button class="btn btn-warning btn-flat btn-block">Back</button>
                                </a>
                            </div>
                            <div class="col-sm-7 col-sm-offset-2">
                                @include('admin.layouts.errors.error')
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('admins.update',$admin->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Name</label>
                                    <input type="text" name="name" class="form-control" id="exampleInputName" placeholder="Enter name" value="{{ $admin->name }}" required>
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputEmail1">Password</label>
                                    <input type="password" name="password" class="form-control" id="exampleInputName" placeholder="Enter new password">
                                </div>

                                <div class="form-group">
                                    <label>Role</label>
                                    <select class="form-control" name="role" required>
                                        @foreach($roles as $role)
                                            <option value="{{ $role->id }}" @if($role->id == $admin->role->id) selected @else  @endif>{{ $role->display_name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary btn-flat">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>
@endsection